### ISSUE TITLE
NPE: void com.appolica.interactiveinfowindow.InfoWindow.setWindowState

### ISSUE THREAD

**Issue by prabint** [Appolica/InteractiveInfoWindowAndroid#15]
Steps:
1. Click on marker so that info window opens
2. Toggle orientation
3. Click on marker  so that info window opens
4. Toggle orientation
5. Click on marker  so that info window opens
Actual: Info window appear on left side of screen and app crashes.

Log:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: my.package.name, PID: 32006
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.appolica.interactiveinfowindow.InfoWindow.setWindowState(com.appolica.interactiveinfowindow.InfoWindow$WindowState)' on a null object reference
                      at com.appolica.interactiveinfowindow.InfoWindowManager$5.onAnimationStart(InfoWindowManager.java:430)
                      at android.view.animation.Animation$1.run(Animation.java:362)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bkolarov-appolica** [comment]
Thank you for your report. This bug has been fixed in our latest release 1.0.5. You can refer to the documentation to see the updates.
