### ISSUE TITLE
Strange error in lolipop or lower level api

### ISSUE THREAD

**Issue by sshuvro58** [Appolica/InteractiveInfoWindowAndroid#5]
This library works fine Marshmallow but If I try this in lower level api , this gives the following error 

**E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.surroundapps.shotorkoporibar, PID: 18891
                                                                                  java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.surroundapps.shotorkoporibar-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.surroundapps.shotorkoporibar-1, /vendor/lib, /data/cust/lib, /system/lib, /data/datalib]]**

I tried the sample app provided with this library

**Comment by deangenovski** [comment]
But this crash is not caused by the sample app but by your own app - com.surroundapps.shotorkoporibar. Does the sample app work for you?

**Comment by sshuvro58** [comment]
@deangenovski  no it didn't work either , here is the full error log

**11-23 18:30:40.684 24195-24195/com.appolica.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.appolica.sample, PID: 24195
                                                                     java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.appolica.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.appolica.sample-1, /vendor/lib, /data/cust/lib, /system/lib, /data/datalib]]
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5148)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4735)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4675)
                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:143)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5392)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.appolica.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.appolica.sample-1, /vendor/lib, /data/cust/lib, /system/lib, /data/datalib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5133)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4735) 
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4675) 
                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:143) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5392) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                         at dalvik.system.NativeStart.main(Native Method)**

**Comment by deangenovski** [comment]
Could you provide some more information regarding your device? What version of Android, what type of device. You are aware that it needs to have google play services, right ?

**Comment by sshuvro58** [comment]
its a tablet . Model Huawei T1701u, Android version 4.4.2  .  Yes I am aware of play services. I can show simple google map in this device, I am not facing any problem regarding google play service And one more this which I couldn't understand at all, why this is showing something related to firebase, while I am not using it

**Comment by sshuvro58** [comment]
@deangenovski  did you able to reproduce the error?

**Comment by deangenovski** [comment]
We will take a look today and let you know.

**Comment by bkolarov-appolica** [comment]
@sshuvro58 it seems that I made a mistake by adding the whole play-services library and you cant build without multidex. Doesn't matter now. I included only the google maps library and created a pull request. Stay tuned for the update in jcenter. 
If you like our work, please give us a star :)

**Comment by bkolarov-appolica** [comment]
@sshuvro58 Published! 

compile 'com.appolica:interactive-info-window:1.0.4'

**Comment by Opriday** [comment]
1: Go to the gradle enable multiDexEnabled and add multidex library in the dependencies.

android {
   ...
   defaultConfig {
      multiDexEnabled true
      ...
   }
}

dependencies {
  // add dependency 
  compile 'com.android.support:multidex:1.0.1'
}

2: Go to the Manifest file and write android:name=".MyApplication" (Class name(MyApplication) is optional you can write whatever you want ).

    <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        .
        .
        .
        .
        .
    </application>

  3: As you wrote android:name=".MyApplication" Inside Application at Manifest file. it will give you an error because you didn't create MyApplication class. Create MyApplication Class extend it by "application" class or Simply click on.MyApplication, a small red balloon appear on the left side of a syntax click on it, you will see (create MyApplication class) in the menu, click on it and Include below Method Inside that class.

    public class MyApplication extends Application {
 
    @Override 
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    } 
 

 If you want to know more then Click on this Link:[https://developer.android.com/studio/build/multidex.html]

hopefully, it works for you.
